FROM python:3.12-slim
WORKDIR /app
COPY . .
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     default-mysql-client \
#     && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt
# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"] 